Software/Scratch/GoPiGoScratch.py
If the user creates other broadcast messages, GoPiGoScratch.py spits out "Wrong command". That's not entirely true. they're perfectly good command, just not meant for GoPiGoScratch. Changed the text to say "Ignoring command" followed by the command in question.
=> Less threatening warning message

Software/Python/gopigo.py
Only tiny changes are needed to get gopigo.py accessible to Python3
(and a new library is needed too - check for that pull request in Raspbian For Robots)
=> bring gopigo.py to Python3

Software/NodeJS/libs/.gitignore, Software/NodeJS/libs/package.json
I found a problem when install `node-gopigo` with `nodejs v6`, because of the version of `i2c-bus`:
```
> i2c-bus@0.11.3 install /home/pi/gamepadgo-client/node_modules/i2c-bus
> node-gyp rebuild
make: Entering directory '/home/pi/gamepadgo-client/node_modules/i2c-bus/build'
CXX(target) Release/obj.target/i2c/src/i2c.o
In file included from ../src/i2c.cc:2:0:
../../nan/nan.h:590:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
v8::Isolate::GCEpilogueCallback callback
^
../../nan/nan.h:590:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
v8::Isolate::GCEpilogueCallback callback
^
../../nan/nan.h:591:18: error: expected primary-expression before ‘gc_type_filter’
, v8::GCType gc_type_filter = v8::kGCTypeAll) {
^
../../nan/nan.h:596:20: error: variable or field …
```
=> Bump i2c-bus

Software/Scratch/GoPiGoScratch.py
Code was supporting GET_DIST for the ultrasonic sensor, but the printed Scratch card handout lists GET DISTANCE
By using regex, we now support both, and additionally GET DIST, and GET_DISTANCE, just because. Otherwise it's too hard to remember whether the _ is needed or not. 
lowercase or uppercase or mixed case are all supported too, as before.
=> Regex for distance sensor

Software/Python/line_follower/line_sensor.py, Software/Python/line_follower/line_sensor_gui.py, Software/Python/line_follower/scratch_line.py
line_sensor.py -> no path was set for the readout files. Using the GUI saved those in home directory.
scratch_line.py -> paths were hardcoded to read from Desktop/GoPiGo/Software/Python/line_follower. Now reading from home directory
line_sensor_gui.py -> libraries were hardcoded to read from Desktop/etc.. which stopped people from using the line follower if they don't have Raspbian for Robots. A more intelligent import is now implemented.
=> Paths cleanup

Software/Scratch/GoPiGoScratch.py
Added some error messages when IR receiver is not enabled but user tries to access it. The messages are showing up in the terminal window so I'm not entirely happy with that. But it's better than crashing and will help customer support. If only we had a way of sending error messages back to Scratch...
=> IR Receiver failing msg

Software/Python/gopigo.py
1. added forward() and backward() as synonyms to fwd() and bwd() They may be longer to type but they're easier to remember for kids, and they match the Scratch commands
2. added turn_right() and turn_left() which takes  degrees as parameters. That way, kids have an easy method of turning the GoPiGo 90 degrees. This code is being migrated from what is already in Scratch.
=> add synonym functions

Setup/install.sh, Software/Python/Examples/Browser_Streaming_Robot/browser_stream_setup.sh, Software/Python/ir_remote_control/script/ir_install_manually.sh
When doing a wget to test internet connectivity in a script file, redirect to /dev/null to avoid leaving behind orphaned index.html files. 
Also avoid using google.com as a test since it is blocked in some countries.
=> no more stray index.html files left behind

Software/Python/ir_remote_control/script/ir_install.sh
1. redirect wget to /dev/null to avoid leaving orphaned index.html files behind
2. don't run apt-get update if being called from DI UPDATE, as it's already been done
3. better user messages (hopefully)
=> make install more efficient when called from DI Update

Software/Scratch/GoPiGoScratch.py
send sensorvalue even on error to allow users to program even if the DHT is not currently plugged in.
Now if there's an error with the DHT it's actually catchable from within Scratch
=> DHT Sensor: Couldn't program the DHT if it wasn't plugged in

Software/Python/line_follower/line_follow.py, Software/Python/line_follower/line_follow1.py, Software/Python/line_follower/line_position.py
By adding "from __future__ import print_function"  we are making certain that all future development will be Python2/3 compatible. At least for the print function and the division.
FYI:   one must also do `sudo pip install -U future` on their SD card for the code to work. This line is already added to DI Update.
=> Added "from __future__"

Software/Python/control_panel/control_panel_gui.py
with the wrong indentation a variable ends up being used before it gets assigned. Fixed.
=> a problem with indentation was killing the gopigo control panel 

Software/Python/easygopigo.py
Why is the line follower library not installed the standard way anyway?
=> Add a try/except around the loading of the line follower library.

Software/Python/line_follower/__init__.py, Software/Python/line_follower/line_sensor.py, Software/Python/setup.py
To import the line sensor, use:
`from line_follower import line_sensor`
Also fix a path issue. Bug means line follower is not currently working.
=> Install Line Follower in a python way

Firmware/gopigo_firmware_update.sh
Here https://github.com/DexterInd/Raspbian_For_Robots/blob/master/upd_script/update_GoPiGo_Firmware.sh#L56 when update_gopigo_firmware is called from "update_GoPiGo_Firmware.sh" the command here https://github.com/DexterInd/GoPiGo/blob/master/Firmware/gopigo_firmware_update.sh#L2 looks for a GoPiGo folder from the path of the file that called it. In case of "~/home/pi/di_update/Raspbian_For_Robots/upd_script/update_GoPiGo_Firmware.sh" there is no GoPiGo folder in its path. Hence update fails. This PR solves it.
=> Changes to support firmware update from di update

Software/Python/ir_remote_control/gobox_ir_receiver_libs/gobox_ir_receiver_monit.conf, Software/Python/ir_remote_control/gobox_ir_receiver_libs/install.sh
Update monit conf paths and be sure to always copy over a fresh copy of gobox_ir_receiver_monit.conf
This should fix issues with scratch and python.
=> Update Monit Conf Paths

Setup/install.sh, Software/Python/line_follower/line_sensor.py
The `line follower` sensor is known for throwing erratic values from time to time.
I've been investigating and I'm almost sure that there's something within the line follower's firmware that sends these (maybe overflowed) values.
This is what we were getting before :
Also, this wasn't the only erratic value we got - there were others which were around `2800`, `6500`, `26000`, etc.
I've implemented the "old" statistical filtering function from the `DHT's` code.
I've had to tweak the following variables in order to get the desired results (I mean about removing the outlier values):
-  `max_buffer_length` - it's an integer and it specifies the buffer length of the list in which we store the values from the sensors.
- `std_factor_threshold` argument - it's a float and the smaller it is, the …
=> hotfix - erratic values when reading from [line follower]

Software/Python/easygopigo.py, Software/Python/ir_remote_control/lirc/install.sh
Ensure folder does exist before copying files
Easygopigo.py >
remove dependency on ir_receiver_check
Missing here are the changes to /boot/config.txt and /etc/modules
=> Make IR Remote work even if not on Raspbian for Robots+  EasyGoPiGo reset_speed()

Setup/install.sh, Software/Python/line_follower/line_sensor.py
Blank files cause the code to crash - which requires try/except (already in, but missing on DexterOS)
=> Install valid line follower files when installing, instead of blank ones

Software/Python/easygopigo.py
We want to avoid classroom contests with the loudness sensor and the sound sensor
=> Limit percent_read to 100%.

README.md, Setup/README.md, Setup/install.sh, Setup/update_gopigo.sh, Software/Python/requirements.txt
This should make the GoPiGo update/install with or without privileges the python package(s).
For updating/installing the python packages of the GoPiGo **with** su privileges the user will run:
```
sudo sh -c "curl -kL dexterindustries.com/update_gopigo | bash"
curl -kL dexterindustries.com/update_gopigo > update_gopigo.sh
sudo bash update_gopigo.sh
```
For updating/installing the python packages of the GoPiGo **without** su privileges the user will run:
```
curl -kL dexterindustries.com/update_gopigo | bash
```
Further tests are still required. We need to make sure `Raspbian For Robots` still works fine, as-well as anything afferent and that `DexterOS` still works fine.
=> hofix - install privileges

Software/Python/ir_remote_control/README.md, Software/Python/ir_remote_control/examples/ir_recv_example.py, Software/Python/ir_remote_control/examples/lirc_example.py, Software/Python/ir_remote_control/server/di_ir_reader.py, Software/Python/ir_remote_control/server/install.sh, Software/Python/ir_remote_control/server/ir_receiver.py
NOTE: the IR sensor still doesn't work 
Make files python 3 ready. 
Reorganise ir_receiver.py so that functions are at the top, and not in the middle of the code, and all constants are together.
Handle cases where we get a byte back instead of a string.
=> fix - IR receiver on Stretch

Software/Python/requirements.txt
When attempting to use the Browser_Streaming_Robot web server, it seems that the package tornado is not installed. This should be listed in the requirements.txt file as a module that is required for the script robot_web_server.py to work properly. See issue [no.296](https://github.com/DexterInd/GoPiGo/issues/296). I've added the name of the package, tornado, to requirements.txt.
=> added tornado to list of required modules

Software/Python/easygopigo.py
On Python3, what we get back from the IR Server is bytes, not strings.
=> make IR Receiver in easygopigo Python3 ready

Software/Python/control_panel/control_panel_gui.py, Software/Python/control_panel/gopigo_control_panel.desktop
Moving Control Panel to wxpython3.
Desktop icon no longer launches a terminal, but directly to Python.
Note: I haven't changed the calls to trimming but I don't think they work. Like, I don't think they worked to start with.
=> rewrite Control Panel

Software/Python/gopigo.py
I have changed the bus on which the GoPiGo communicates with the Raspberry Pi. It's now set to use `RPI_1SW`. 
This has also been tested and works as expected.
=> hotfix - use SW I2C instead of the Raspberry Pi's HW I2C
