Software/NodeJS/gopigo.commands.js, Software/NodeJS/gopigo.js, Software/NodeJS/package.json
Add enc_read command + function
Add trim_test, trim_write, trim_read commands + functions
=> Porting changes from the Python library

Software/Scratch/GoPiGoScratch.py
I just wanted to share some of the modifications I made to the Scratch interface. I am not a developer, so I hope my edits are consistent with the current style.
=> Scratchsensors

Software/CSharp/Driver/StartupTask.cs
clean up run method so users who download library have a clean slate
=> Cleanup run method

Software/Scratch/GoPiGoScratch.py
Button, Light, Sound, Ultrasonic distance, Buzzer, LED, Motion, IR
receiver, DI line sensor
=> Scratch sensors added for the GoPiGo

Software/C/README.md, Software/C/basic_test_all.c, Software/C/gopigo.c, Software/C/gopigo.h
Added header file and basic structure.
=> header file and started basic_test_all file

Software/C/basic_test_all.c, Software/C/gopigo.c, Software/C/gopigo.h
-Functions till digitalWrite added
-Have to be tested
=> More functions and license added

Software/NodeJS/README.md
I lost many hours when starting with nodeJs
=> add .Gopigo at the end when include in the readme file

Firmware/firmware_update.sh
=> Small typo

Software/Python/line_follower/line_sensor_gui.py, Software/Python/line_follower/scratch_line.py, Software/Scratch/GoPiGoScratch.py
- More granularity added -4 to 7 in output
- GUI updated
=> Line follower GUI and scratch code update

Software/C/basic_test_all.c, Software/C/gopigo.c, Software/C/gopigo.h
Port of python functions to enable handling of wheel encoders.
Additionally contains indentation cleanup by using spaces instead of tabs and removing unnecessary white spaces and defines.
=> Encoder support

Software/C/basic_test_all.c, Software/C/gopigo.c
fix the activation of LED by writing correct 'value' pin
=> fix LED activation

Setup/install.sh
Peaple can't visit google.com in China, try to use raspberrypi.org to check connection instead.
=> google is blocked in China, use raspberrypi.org  instead

Software/C/gopigo.c, Software/C/gopigo.h
Implement the read_motor_speed function with values returned by call-by-reference
=> Read speed

Software/Python/control_panel/control_panel_gui.py
=> GoPiGo control panel GUI updated

Software/Python/gopigo.py
- Added support with winrt_smbus.py
- also make some changes for python 3 compatibility
- remove some unused imports
=> Added support with winrt_smbus.py

Software/Scratch/GoPiGoScratch.py
Forum thread for reference http://www.dexterindustries.com/topic/audio-sensor-problems/
=> fixed an issue with Sound sensor

Setup/install.sh
Since gpg has been renamed to gopigo, the install script should keep up and get the memo.
=> install the newly named gopigo binary properly

Setup/install.sh, Software/Python/ir_remote_control/script/ir_install.sh
If those scripts are run from DI Update, they will no longer tell the user to reboot.
Otherwise behaviour is as before.
=> Quiet mode for Gopigo scripts

Setup/install.sh
Indicate to user that script requires sudo
remove leftover index.html files that were getting created when connectivity's being tested
No longer assume that the files are getting installed on Desktop.
=> make install script a bit stronger. 

Software/Scratch/GoPiGoScratch.py
Simple cleanup of the code handling the sound sensor.
=> Sound cleanup

Software/Python/line_follower/line_sensor_gui.py
Changed the Window frame size and the spacing of the buttons.
The problem was this window had the buttons overlapping the text when viewed on a full screen like the monitor, So I have changed the window size, the x-axis of the buttons to change the spacing between them and also their Y axis to not to overlap over the Instructions.
=> Change of spacing between the buttons

Software/Python/ir_remote_control/gobox_ir_receiver_libs/di_ir_reader.py, Software/Python/ir_remote_control/gobox_ir_receiver_libs/di_ir_reader_wrapper_monit.sh, Software/Python/ir_remote_control/gobox_ir_receiver_libs/gobox_ir_receiver_monit.conf, Software/Python/ir_remote_control/gobox_ir_receiver_libs/install.sh, Software/Python/ir_remote_control/gobox_ir_receiver_libs/ir_debug_logger.py, Software/Python/ir_remote_control/gobox_ir_receiver_libs/ir_receiver.py, Software/Python/ir_remote_control/gobox_ir_receiver_libs/ir_receiver_example.py, Software/Python/ir_remote_control/gobox_ir_receiver_libs/monitrc, Software/Python/ir_remote_control/gobox_ir_receiver_libs/setup.py, Software/Scratch/GoPiGoScratch.py
- Python libraries added
- Scratch updated
- install script added
- monit added
=> Ir receiver software updated to add noise removal from the IR signals 

Software/Python/ir_remote_control/gobox_ir_receiver_libs/install.sh
(minor cleanup for Raspbian for Robots update)
=> Filepaths updated

Software/Scratch/GoPiGoScratch.py
add FOLDER to set folder where to save photos 
change userid on photos so users can erase their photos
How to use:
broadcast join FOLDER <foldername> 
broadcast TAKE_PICTURE
if FOLDER is not set, then it defaults to /home/pi/Desktop as before
when setting FOLDER, keep in mind that it's relative to /home/pi/Desktop/
=> add FOLDER to the list of Scratch commands to set folder where to save photos

Setup/install.sh
Added the necessary lines to activate Python3 support by default.
=> automatic install for Python3

Software/Python/Examples/Browser_Streaming_Robot/README.md
ReadME of Browser Streaming Robot
=> Updating ReadME

Software/Scratch/GoPiGoScratch.py
eSpeak support for GoPiGo
Use Broadcast Join SPEAK <your text>
=> eSpeak support

Software/Scratch/GoPiGoScratch.py
=> Support for PivotPi

Software/Python/easygopigo.py, Software/Python/setup.py
Here's easygopigo.py  
A library meant for easy access to the GoPiGo sensors
=> small change for remote, and add easygopigo to system-wide libraries

Setup/install.sh
@karan259 and @CleoQc and @Shoban94 can you check that this is a good idea?
=> Wiringpi update 201612

Software/Python/ir_remote_control/script/ir_install.sh
the tests for quiet_mode were generating an error and were not running properly
=> fix ir_install.sh for quiet_mode

Setup/install.sh
1. install script_tools in case this is run as a standalone
2. source functions_library.sh
3. make use of the feedback function, and the quiet_mode function
but most importantly
4. call wiringpi.sh from the script_tools folder
=> Fix WiringPi call

Firmware/firmware_update.sh, Firmware/gopigo_firmware_update.sh
- This should let the GUI run the firmware update directly by calling
the script
=> GoPiGo firmware update uses functions

Software/Python/ir_remote_control/script/ir_install.sh
Changed the path for lircrc_keyes
=> Fixing a typo

Software/Python/easygopigo.py
@karan259  Do you agree? 
I'm taking 3 readings and averaging them. 
I'm also limiting the ultrasonic sensor to a distance of 5m, discarding anything higher than that. 
This only touches easygopigo.py
=> Make ultrasonic sensor a bit more stable

Software/Python/easygopigo.py
cannot set the buzzer to a negative power.
keep track of current buzzer power level
=> changes to the buzzer class:

Software/Python/easygopigo.py, Software/Python/gopigo.py
corrected_us_dist(pin) does a linear correction for us_dist() 
The factors are based on a regression calculated with values from 5 or 6 US sensors across three continents.
Corrected values do help but as each sensor is an individual, success will differ across different sensors.
=> Introduce a linear correction for the ultrasonic sensor

Firmware/firmware_update.sh, Firmware/gopigo_firmware_update.sh, Setup/gopigo
There are few more to be changed in these folders GoPiGo_Scratch_Scripts, Troubleshoot and ir_remote_control.
=> Adding a variable to get REPO PATH

Software/Python/easygopigo.py
First, before each read, wait till the bus is available
Second, confirm the bus is open before doing the read (in case another thread got it)
Third, grab the read flag
Fourth do the read
Fifth, release the read flag asap for other threads
This only works for one process and only if all readings go through easygopigo
More than one process would still experience issues, but a single multi threaded process would be safe.
=> Attempt at making easygopigo thread_safe

Software/Python/easygopigo.py
Add left(), backward(), forward(), right(), and stop()
If easygopigo is imported after gopigo, then these fcts are called.
If gopigo is imported after easygopigo, the original fcts are called.
=> Add some GPG control

Software/Python/easygopigo.py
> add a gpg parameter when creating an instance
> said gpg is defaulted to None and is not used anywhere
> users don't need to provide it
Signed-off-by: CleoQc <cleoqc1124@gmail.com>
=> prepare easygopigo library for later upgrade

Software/Python/easygopigo.py
Some USB tools
And EasyCamera class that saves photos to a USB key
=> add USB support and EasyCamera class

Software/Python/easygopigo.py
remember port information, and reduce distance to 3m
=> Ultrasonic sensor:

Software/Python/easygopigo.py
this is needed to support the servo
=> Add SERVO as a supported port

Software/Python/I2C_mutex.py, Software/Python/easygopigo.py, Software/Python/gopigo.py
Use Matt's suggestion for mutex. 
I created I2C_mutex.py  which should be a pretty stable file
=> first pass at Mutex

Software/Python/easygopigo.py
renamed the functions that deal with thread/process protection to their previous names so it will be possible to piggyback other functionalities (like thread safe, if need be)
=> distance sensor needs process/thread protection around its instantiation

Software/Python/easygopigo.py
PiCamera made easygopigo slow to load. Removed it.
=> Move PiCamera wrapper out of easygopigo

Software/Python/easygopigo.py, Software/Python/gopigo.py
Remove unneeded libraries from easygopigo 
optimize version detection in gopigo, thanks to @RobertLucian for this one
=> EasyGopigo and GoPiGo optimization

Software/Python/easygopigo.py
Easygopigo is currently available but not the distance sensor code yet.
Also put a bunch of other try/except around mutex and gopigo access.
re-organised the order of the methods in the EasyGoPiGo class, which gives a weird diff in github.
=> Put all Distance Sensor code inside try/except

Software/Python/easygopigo.py, Software/Python/gopigo.py
At least we print error messages now
=> better error handling. Well, sort of. 

Software/Python/easygopigo.py, Software/Python/line_follower/line_sensor.py, Software/Python/line_follower/scratch_line.py
better error handling when line follower cannot be connected to.
=> Line follower updates

Software/Python/sensor_examples/dht/Adafruit_Python_DHT/Adafruit_DHT/Raspberry_Pi.py, Software/Python/sensor_examples/dht/Adafruit_Python_DHT/Adafruit_DHT/common.py, Software/Python/sensor_examples/dht/Adafruit_Python_DHT/Adafruit_DHT/platform_detect.py, Software/Python/sensor_examples/dht/Adafruit_Python_DHT/setup.py, Software/Python/sensor_examples/dht/Adafruit_Python_DHT/source/Raspberry_Pi/pi_mmio.c
Latest version detects Raspberry Pi 3.
=> Upgrade Adafruit DHT library 

Software/Python/easygopigo.py
Add a is_button_pressed in the ButtonSensor class in easygopigo.
Returns True or False according to button state.
Button can be in port A1 or D11
=> easygopigo: is_button_pressed in ButtonSensor class

Software/Python/easygopigo.py, Software/Python/ir_remote_control/server/ir_receiver.py
Remote Sensor Class, get_remote_code()  will return the key being pressed for as long as it's being pressed. Returns an empty string if no key is pressed.
=> Support non consuming remote reading

Software/Python/line_follower/scratch_line.py
=> move scratch_line exception handling in line with python3

Software/Python/easygopigo.py
Note, this Grove DHT support no longer calls the dht functions found in gopigo.py but those found in DI_Sensors.  Therefore DI_Sensors must be available
Loudness sensor pretty straightforward
=> Added Loudness sensor and DHT sensor

Software/Python/easygopigo.py
read_position_str() is needed mostly for Bloxter 
This PR is equivalent to https://github.com/DexterInd/GoPiGo3/pull/145
=> read_position_str() is also needed here to keep in sync with easygopigo3

Software/Python/tests/firmware_version_cpu_test.py
=> hotfix - bad print format caused by old python version

Software/C/gopigo.c, Software/C/gopigo.h
This commits adds function `led_toggle(int l_id, bool onoff)` to header and introduces some minor changes for whitespace removal and constant definition of file paths and addresses.
=> Add led_toggle to header

Software/Python/gopigo.py
=> Remove comment

Software/Python/gopigo.py
Add documentation for a few of the functions in the Python gopigo library.
I've yet to test out the updated file on a GoPiGo2, but I'll do this sometime in the next few days. Since this just makes changes to the documentation it shouldn't effect the functionality, but I'll try it out just to make sure.
Let me know if there are any changes you would like me to make to the added documentation.
=> Document several python gopigo functions

Setup/update_gopigo.sh
This fixes the issue where RFR_Tools can't install some bits of it because it can't source script_tools.
=> hotfix - install script_tools before rfr_tools

Setup/update_gopigo.sh
This reverts commit b7bd4a567b3cc8673aece5ea420073d887ff4c95.
This didn't seem to solve the issue. On systems where `git` is not installed, the update/install no longer gets through.
=> Revert "hotfix - install script_tools before rfr_tools (#314)"

Setup/README.md, Setup/install.sh, Setup/update_gopigo.sh
Requires https://github.com/DexterInd/RFR_Tools/pull/13. Now the GUI installation can be bypassed.
=> hotfix - add gui option & optimize install script

Projects/Empathybot/README.md, Software/Python/easygopigo.py, Software/Python/gopigo.py
Implement support for Bloxter/GPG2/Line follower without breaking backward compatibility.
Bit of a hack but should be totally transparent to the user.
=> Bloxter, red line follower and backward compatibility
